// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BookIndex>>
abstract class BookIndex implements RustOpaqueInterface {
  bool addBook(
      {required String title,
      required String text,
      required BigInt id,
      required BigInt line});

  bool commit();

  static BookIndex? create() =>
      RustLib.instance.api.crateApiSearchEngineBookIndexCreate();

  List<SearchResult> search({required String query});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SearchResult>>
abstract class SearchResult implements RustOpaqueInterface {
  BigInt get id;

  BigInt get line;

  String get text;

  String get title;

  set id(BigInt id);

  set line(BigInt line);

  set text(String text);

  set title(String title);
}
